package golang

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"os"
	"path"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/nanoteck137/pyrin/spark"
	"github.com/nanoteck137/pyrin/utils"
)

const indent = "\t"
const warningMessage = "DO NOT EDIT THIS: This file was generated by the Pyrin Golang Generator"

//go:embed base_client.go.txt
var baseClientSource string

var _ spark.Generator = (*GolangGenerator)(nil)

type GolangGenerator struct{}

func (g *GolangGenerator) Generate(serverDef *spark.ServerDef, resolver *spark.Resolver, outputDir string) error {
	buf := &bytes.Buffer{}
	err := g.generateTypeDefinitionCode(buf, resolver)
	if err != nil {
		return err
	}

	p := path.Join(outputDir, "types.go")
	err = os.WriteFile(p, buf.Bytes(), 0644)
	if err != nil {
		return err
	}

	buf = &bytes.Buffer{}
	err = g.generateClientCode(buf, serverDef)
	if err != nil {
		return err
	}

	p = path.Join(outputDir, "client.go")
	err = os.WriteFile(p, buf.Bytes(), 0644)
	if err != nil {
		return err
	}

	p = path.Join(outputDir, "base_client.go")
	err = os.WriteFile(p, []byte(baseClientSource), 0644)
	if err != nil {
		return err
	}

	return nil
}

func (g *GolangGenerator) generateTypeDefinitionCode(out io.Writer, resolver *spark.Resolver) error {
	w := spark.NewCodeWriter(out, indent)

	w.IndentWritef("// %s\n", warningMessage)
	w.IndentWritef("package api\n")
	w.IndentWritef("\n")

	for _, s := range resolver.Symbols {
		if s.State != spark.SymbolResolved {
			continue
		}

		rs := s.ResolvedStruct

		err := g.generateStruct(&w, rs)
		if err != nil {
			return err
		}
	}

	return nil
}

func (g *GolangGenerator) generateStruct(w *spark.CodeWriter, rs *spark.ResolvedStruct) error {
	w.IndentWritef("type %s struct {\n", rs.Name)

	w.Indent()
	for _, field := range rs.Fields {
		err := w.WriteIndent()
		if err != nil {
			return err
		}

		g.generateField(w, &field)
	}
	w.Unindent()

	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)

	// w.Writef("});\n")
	// w.Writef("\n")
	// w.Writef("export type %s = z.infer<typeof %s>;\n", rs.Name, rs.Name)
	// w.Writef("\n")

	return nil
}

func (g *GolangGenerator) generateFieldType(w io.Writer, ty spark.FieldType) {
	switch t := ty.(type) {
	case *spark.FieldTypeString:
		fmt.Fprint(w, "string")
	case *spark.FieldTypeInt:
		fmt.Fprint(w, "int")
	case *spark.FieldTypeBoolean:
		fmt.Fprint(w, "bool")
	case *spark.FieldTypeArray:
		fmt.Fprintf(w, "[]")
		g.generateFieldType(w, t.ElementType)
	case *spark.FieldTypePtr:
		fmt.Fprintf(w, "*")
		g.generateFieldType(w, t.BaseType)
	default:
		// TODO(patrik): Better error
		panic("Unknown type")
	}
}

func (g *GolangGenerator) generateField(w *spark.CodeWriter, field *spark.ResolvedField) {
	jsonName := field.Name
	name := strcase.ToCamel(field.Name)

	_, isPointer := field.Type.(*spark.FieldTypePtr)

	w.Writef("%s ", name)
	g.generateFieldType(w, field.Type)
	w.Writef(" `")
	w.Writef("json:\"")
	w.Writef("%s", jsonName)
	// TODO(patrik): Should this be here?
	if isPointer {
		w.Writef(",omitempty")
	}
	w.Writef("\"")

	w.Writef("`")
	w.Writef("\n")
}

func generateApiEndpoint(w *spark.CodeWriter, e *spark.Endpoint) error {
	newPath, args := utils.ReplacePathArgs(e.Path, nil, func(name string) string {
		return "%v"
	})

	resType := e.Response
	if resType == "" {
		resType = "any"
	}

	b := strings.Builder{}

	for _, v := range args {
		fmt.Fprintf(&b, "%s string, ", v)
	}

	if e.Body != "" {
		fmt.Fprintf(&b, "body %s, ", e.Body)
	}

	fmt.Fprintf(&b, "options Options")

	w.IndentWritef("func (c *Client) %v(%s) (*%s, error) {\n", e.Name, b.String(), resType)
	w.Indent()

	if len(args) > 0 {
		b := strings.Builder{}
		for _, v := range args {
			fmt.Fprintf(&b, ", %s", v)
		}

		w.IndentWritef("path := Sprintf(\"%v\"%s)\n", newPath, b.String())
	} else {
		w.IndentWritef("path := \"%v\"\n", e.Path)
	}

	w.IndentWritef("url, err := createUrl(c.addr, path, options.QueryParams)\n")
	w.IndentWritef("if err != nil {\n")
	w.Indent()
	w.IndentWritef("return nil, err\n")
	w.Unindent()
	w.IndentWritef("}\n")

	w.Writef("\n")

	w.IndentWritef("data := RequestData{\n")
	w.Indent()

	w.IndentWritef("Url: url,\n")
	w.IndentWritef("Method: \"%v\",\n", e.Method)
	w.IndentWritef("AuthToken: c.authToken,\n")
	w.IndentWritef("ApiToken: c.apiToken,\n")

	body := "nil"
	if e.Body != "" {
		body = "body"
	}

	w.IndentWritef("Body: %s,\n", body)

	w.Unindent()
	w.IndentWritef("}\n")

	w.IndentWritef("return Request[%s](data)\n", resType)

	w.Unindent()
	w.IndentWritef("}\n")

	return nil
}

// func generateFormApiEndpoint(w *utils.CodeWriter, e *spec.FormApiEndpoint) error {
// 	var args []string
// 	parts := strings.Split(e.Path, "/")
// 	endpointHasArgs := false
//
// 	for i, p := range parts {
// 		if len(p) == 0 {
// 			continue
// 		}
//
// 		if p[0] == ':' {
// 			name := p[1:]
// 			args = append(args, name)
//
// 			parts[i] = fmt.Sprintf("${%s}", name)
//
// 			endpointHasArgs = true
// 		}
// 	}
//
// 	newEndpoint := strings.Join(parts, "/")
//
// 	w.IWritef("%s(", strcase.ToLowerCamel(e.Name))
//
// 	for _, arg := range args {
// 		w.Writef("%s: string, ", arg)
// 	}
//
// 	w.Writef("formData: FormData, ")
// 	w.Writef("options?: ExtraOptions")
//
// 	w.Writef(") {\n")
//
// 	w.Indent()
//
// 	w.IWritef("return this.requestWithFormData(")
//
// 	if endpointHasArgs {
// 		w.Writef("`%s`", newEndpoint)
// 	} else {
// 		w.Writef("\"%s\"", newEndpoint)
// 	}
//
// 	w.Writef(", \"%s\"", e.Method)
//
// 	if e.ResponseType != "" {
// 		w.Writef(", api.%s", e.ResponseType)
// 	} else {
// 		w.Writef(", z.undefined()")
// 	}
//
// 	w.Writef(", z.undefined()")
//
// 	w.Writef(", formData")
//
// 	w.Writef(", options")
//
// 	w.Writef(")\n")
// 	w.Unindent()
//
// 	w.IWritef("}\n")
//
// 	return nil
// }

func (g *GolangGenerator) generateClientCode(w io.Writer, serverDef *spark.ServerDef) error {
	cw := spark.NewCodeWriter(w, indent)

	cw.IndentWritef("// DO NOT EDIT THIS: This file was generated by the Pyrin Golang Generator\n")
	cw.IndentWritef("package api\n")
	cw.Writef("\n")

	for _, endpoint := range serverDef.Endpoints {
		cw.IndentWritef("\n")

		switch endpoint.Type {
		case spark.EndpointTypeApi:
			err := generateApiEndpoint(&cw, &endpoint)
			if err != nil {
				return err
			}
		}
	}

	// for _, endpoint := range server.FormApiEndpoints {
	// 	cw.IWritef("\n")
	//
	// 	err := generateFormApiEndpoint(&cw, &endpoint)
	// 	if err != nil {
	// 		return err
	// 	}
	// }

	// TODO(patrik): Add normal endpoints with just normal fetch calls

	return nil
}
